baseurl = "http://cs.brown.edu/~ksinghal/"
languageCode = "en-us"
title = "kartik@BrownCS:~"
theme = "base16"

canonifyURLs = "true"

[params]
  author = "Kartik Singhal"
  description = "Homepage of Kartik Singhal on Brown CS Web"
  copyright = "Copyright © 2016 Kartik Singhal."
